"""many-to-many relationship between therapist annotations and dialog turns

Revision ID: 05243b011f6e
Revises: 4fa61cab1a99
Create Date: 2023-09-25 12:38:23.711321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05243b011f6e'
down_revision = '4fa61cab1a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationtherapist_dialogturn',
    sa.Column('id_dialog_turn', sa.Integer(), nullable=True),
    sa.Column('id_annotation_therapist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_annotation_therapist'], ['ps_dialog_turn_annotation_therapist.id'], name=op.f('fk_annotationtherapist_dialogturn_id_annotation_therapist_ps_dialog_turn_annotation_therapist')),
    sa.ForeignKeyConstraint(['id_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_annotationtherapist_dialogturn_id_dialog_turn_ps_dialog_turn'))
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_therapist', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ps_dialog_turn_annotation_therapist_id_ps_dialog_turn_ps_dialog_turn', type_='foreignkey')
        batch_op.drop_column('id_ps_dialog_turn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation_therapist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ps_dialog_turn', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_ps_dialog_turn_annotation_therapist_id_ps_dialog_turn_ps_dialog_turn', 'ps_dialog_turn', ['id_ps_dialog_turn'], ['id'])

    op.drop_table('annotationtherapist_dialogturn')
    # ### end Alembic commands ###
