"""separate label_d columns for client and therapist

Revision ID: 0708a4d6a80d
Revises: 5bd1ea5df646
Create Date: 2023-09-07 09:37:18.198346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0708a4d6a80d"
down_revision = "5bd1ea5df646"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_d_client",
                sa.Enum(
                    "hard_negative",
                    "soft_negative",
                    "neutral",
                    "positive",
                    name="sublabelsdclient",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "label_d_therapist",
                sa.Enum(
                    "restructuring",
                    "suggest_change",
                    "encouragement",
                    "advice",
                    "other",
                    name="sublabelsdtherapist",
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("label_d")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("label_d", sa.VARCHAR(length=9), nullable=True))
        batch_op.drop_column("label_d_therapist")
        batch_op.drop_column("label_d_client")

    # ### end Alembic commands ###
