"""seprate dialog turn annotations table into multiple

Revision ID: 0a2130aa229e
Revises: e4c699f4e9a2
Create Date: 2023-09-20 15:46:48.859873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2130aa229e'
down_revision = 'e4c699f4e9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_dialog_turn_annotation_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('label_a', sa.Enum('attachment', 'identity', 'security', 'excitement', 'other', name='sublabelsaclient'), nullable=True),
    sa.Column('label_b', sa.Enum('attachment', 'identity', 'security', 'excitement', 'other', name='sublabelsbclient'), nullable=True),
    sa.Column('label_c', sa.Enum('acceptance', 'esteem', 'fight', 'flight', 'other', name='sublabelscclient'), nullable=True),
    sa.Column('label_d', sa.Enum('hard_negative', 'soft_negative', 'neutral', 'positive', name='sublabelsdclient'), nullable=True),
    sa.Column('label_e', sa.Enum('insight', name='sublabelseclient'), nullable=True),
    sa.Column('label_f', sa.Enum('no_change', 'switch', 'escalation', name='sublabelsfclient'), nullable=True),
    sa.Column('strength_a', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthaclient'), nullable=True),
    sa.Column('strength_b', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthbclient'), nullable=True),
    sa.Column('strength_c', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthcclient'), nullable=True),
    sa.Column('strength_d', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthdclient'), nullable=True),
    sa.Column('strength_e', sa.Enum('no_recognition', 'low_recognition', 'moderate_recognition', 'good_recognition', 'excellent_recognition', name='labelstrengtheclient'), nullable=True),
    sa.Column('strength_f', sa.Enum('significant_deterioration', 'some_deterioration', 'no_change', 'some_improvement', 'significant_improvement', name='labelstrengthfclient'), nullable=True),
    sa.Column('comment_a', sa.Text(), nullable=True),
    sa.Column('comment_b', sa.Text(), nullable=True),
    sa.Column('comment_c', sa.Text(), nullable=True),
    sa.Column('comment_d', sa.Text(), nullable=True),
    sa.Column('comment_e', sa.Text(), nullable=True),
    sa.Column('comment_f', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_ps_dialog_turn', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_dialog_turn_annotation_client_id_dataset_dataset')),
    sa.ForeignKeyConstraint(['id_ps_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_ps_dialog_turn_annotation_client_id_ps_dialog_turn_ps_dialog_turn')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_ps_dialog_turn_annotation_client_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_dialog_turn_annotation_client'))
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ps_dialog_turn_annotation_client_timestamp'), ['timestamp'], unique=False)

    op.create_table('ps_dialog_turn_annotation_dyad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('label_a', sa.Enum('bond', 'tasks_goals', name='sublabelsadyad'), nullable=True),
    sa.Column('label_b', sa.Enum('confrontational', 'withdrawal', 'other', name='sublabelsbdyad'), nullable=True),
    sa.Column('strength_a', sa.Enum('low', 'medium', 'high', name='labelstrengthadyad'), nullable=True),
    sa.Column('strength_b', sa.Enum('high', 'medium', 'low', name='labelstrengthbdyad'), nullable=True),
    sa.Column('comment_a', sa.Text(), nullable=True),
    sa.Column('comment_b', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_ps_dialog_turn', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_dialog_turn_annotation_dyad_id_dataset_dataset')),
    sa.ForeignKeyConstraint(['id_ps_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_ps_dialog_turn_annotation_dyad_id_ps_dialog_turn_ps_dialog_turn')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_ps_dialog_turn_annotation_dyad_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_dialog_turn_annotation_dyad'))
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_dyad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ps_dialog_turn_annotation_dyad_timestamp'), ['timestamp'], unique=False)

    op.create_table('ps_dialog_turn_annotation_therapist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('label_a', sa.Enum('emotional', 'cognitive', 'respect', 'calming', 'other', name='sublabelsatherapist'), nullable=True),
    sa.Column('label_b', sa.Enum('interpretation', 'reframing', 'reflection', 'transference', 'other', name='sublabelsbtherapist'), nullable=True),
    sa.Column('label_c', sa.Enum('questions', 'exploration', 'upregulation', 'other', name='sublabelsctherapist'), nullable=True),
    sa.Column('label_d', sa.Enum('restructuring', 'suggest_change', 'encouragement', 'advice', 'other', name='sublabelsdtherapist'), nullable=True),
    sa.Column('label_e', sa.Enum('general_helpfulness', name='sublabelsetherapist'), nullable=True),
    sa.Column('strength_a', sa.Enum('low', 'medium', 'high', name='labelstrengthatherapist'), nullable=True),
    sa.Column('strength_b', sa.Enum('low', 'medium', 'high', name='labelstrengthbtherapist'), nullable=True),
    sa.Column('strength_c', sa.Enum('low', 'medium', 'high', name='labelstrengthctherapist'), nullable=True),
    sa.Column('strength_d', sa.Enum('low', 'medium', 'high', name='labelstrengthdtherapist'), nullable=True),
    sa.Column('strength_e', sa.Enum('low', 'medium', 'high', name='labelstrengthetherapist'), nullable=True),
    sa.Column('comment_a', sa.Text(), nullable=True),
    sa.Column('comment_b', sa.Text(), nullable=True),
    sa.Column('comment_c', sa.Text(), nullable=True),
    sa.Column('comment_d', sa.Text(), nullable=True),
    sa.Column('comment_e', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_ps_dialog_turn', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_dialog_turn_annotation_therapist_id_dataset_dataset')),
    sa.ForeignKeyConstraint(['id_ps_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_ps_dialog_turn_annotation_therapist_id_ps_dialog_turn_ps_dialog_turn')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_ps_dialog_turn_annotation_therapist_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_dialog_turn_annotation_therapist'))
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_therapist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ps_dialog_turn_annotation_therapist_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_index('ix_ps_dialog_turn_annotation_timestamp')

    op.drop_table('ps_dialog_turn_annotation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_dialog_turn_annotation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('label_a_client', sa.VARCHAR(length=10), nullable=True),
    sa.Column('label_a_therapist', sa.VARCHAR(length=9), nullable=True),
    sa.Column('label_a_dyad', sa.VARCHAR(length=11), nullable=True),
    sa.Column('label_b_client', sa.VARCHAR(length=10), nullable=True),
    sa.Column('label_b_therapist', sa.VARCHAR(length=14), nullable=True),
    sa.Column('label_b_dyad', sa.VARCHAR(length=15), nullable=True),
    sa.Column('label_c_client', sa.VARCHAR(length=10), nullable=True),
    sa.Column('label_c_therapist', sa.VARCHAR(length=12), nullable=True),
    sa.Column('label_d_client', sa.VARCHAR(length=13), nullable=True),
    sa.Column('label_d_therapist', sa.VARCHAR(length=14), nullable=True),
    sa.Column('label_e_client', sa.VARCHAR(length=7), nullable=True),
    sa.Column('label_e_therapist', sa.VARCHAR(length=19), nullable=True),
    sa.Column('label_f_client', sa.VARCHAR(length=10), nullable=True),
    sa.Column('strength_a_client', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_b_client', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_c_client', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_d_client', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_e_client', sa.VARCHAR(length=21), nullable=True),
    sa.Column('strength_a_therapist', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_b_therapist', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_c_therapist', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_d_therapist', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_e_therapist', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_a_dyad', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_b_dyad', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_f_client', sa.VARCHAR(length=25), nullable=True),
    sa.Column('comment_a', sa.TEXT(), nullable=True),
    sa.Column('comment_b', sa.TEXT(), nullable=True),
    sa.Column('comment_c', sa.TEXT(), nullable=True),
    sa.Column('comment_d', sa.TEXT(), nullable=True),
    sa.Column('comment_e', sa.TEXT(), nullable=True),
    sa.Column('comment_f', sa.TEXT(), nullable=True),
    sa.Column('comment_summary', sa.TEXT(), nullable=True),
    sa.Column('speaker', sa.VARCHAR(length=9), nullable=True),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.Column('id_ps_dialog_turn', sa.INTEGER(), nullable=True),
    sa.Column('id_dataset', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name='fk_ps_dialog_turn_annotation_id_dataset_dataset'),
    sa.ForeignKeyConstraint(['id_ps_dialog_turn'], ['ps_dialog_turn.id'], name='fk_ps_dialog_turn_annotation_id_ps_dialog_turn_ps_dialog_turn'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='fk_ps_dialog_turn_annotation_id_user_user'),
    sa.PrimaryKeyConstraint('id', name='pk_ps_dialog_turn_annotation')
    )
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.create_index('ix_ps_dialog_turn_annotation_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('ps_dialog_turn_annotation_therapist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_dialog_turn_annotation_therapist_timestamp'))

    op.drop_table('ps_dialog_turn_annotation_therapist')
    with op.batch_alter_table('ps_dialog_turn_annotation_dyad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_dialog_turn_annotation_dyad_timestamp'))

    op.drop_table('ps_dialog_turn_annotation_dyad')
    with op.batch_alter_table('ps_dialog_turn_annotation_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_dialog_turn_annotation_client_timestamp'))

    op.drop_table('ps_dialog_turn_annotation_client')
    # ### end Alembic commands ###
