"""new psychotherapy data structure

Revision ID: 0d2634ef6bb6
Revises: 220e96ed47d2
Create Date: 2023-07-03 13:58:50.388424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2634ef6bb6'
down_revision = '220e96ed47d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_dialog_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_n', sa.Integer(), nullable=True),
    sa.Column('event_speaker', sa.String(length=64), nullable=True),
    sa.Column('event_plaintext', sa.Text(), nullable=True),
    sa.Column('id_ps_dialog_turn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_ps_dialog_event_id_ps_dialog_turn_ps_dialog_turn')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_dialog_event'))
    )
    with op.batch_alter_table('ps_dialog_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('main_speaker', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('session_n', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dialog_turn_n', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_ps_dialog_turn_event_id')
        batch_op.drop_index('ix_ps_dialog_turn_t_init')
        batch_op.drop_column('event_speaker')
        batch_op.drop_column('event_text')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('event_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('event_speaker', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_ps_dialog_turn_t_init', ['t_init'], unique=False)
        batch_op.create_index('ix_ps_dialog_turn_event_id', ['event_id'], unique=False)
        batch_op.drop_column('dialog_turn_n')
        batch_op.drop_column('session_n')
        batch_op.drop_column('main_speaker')
        batch_op.drop_column('timestamp')

    op.drop_table('ps_dialog_event')
    # ### end Alembic commands ###
