"""new table to store evidence for dyad annotations

Revision ID: 14ef024f9b6c
Revises: 2cdbb94227e2
Create Date: 2023-09-28 10:32:07.140512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ef024f9b6c'
down_revision = '2cdbb94227e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_dyad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_dialog_event', sa.Integer(), nullable=True),
    sa.Column('id_ps_annotation_dyad', sa.Integer(), nullable=True),
    sa.Column('label', sa.Enum('label_a', 'label_b', name='labelnamesdyad'), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name=op.f('fk_evidence_dyad_id_ps_annotation_dyad_ps_annotation_dyad')),
    sa.ForeignKeyConstraint(['id_ps_dialog_event'], ['ps_dialog_event.id'], name=op.f('fk_evidence_dyad_id_ps_dialog_event_ps_dialog_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_dyad'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_dyad')
    # ### end Alembic commands ###
