"""rename id_user column to id_author

Revision ID: 179c4bee53ca
Revises: 09b49a721de0
Create Date: 2023-06-20 16:56:04.468188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179c4bee53ca'
down_revision = '09b49a721de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_author', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_dataset_id_user_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dataset_id_author_user'), 'user', ['id_author'], ['id'])
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_dataset_id_author_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_dataset_id_user_user', 'user', ['id_user'], ['id'])
        batch_op.drop_column('id_author')

    # ### end Alembic commands ###
