"""association table between annotations and schema for therapist

Revision ID: 189cf70c7b8b
Revises: d2a9e906e825
Create Date: 2023-10-24 23:06:37.484794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189cf70c7b8b'
down_revision = 'd2a9e906e825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationtherapist_annotationschema',
    sa.Column('id_ps_annotation_therapist', sa.Integer(), nullable=True),
    sa.Column('id_therapist_annotation_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name=op.f('fk_annotationtherapist_annotationschema_id_ps_annotation_therapist_ps_annotation_therapist')),
    sa.ForeignKeyConstraint(['id_therapist_annotation_schema'], ['therapist_annotation_schema.id'], name=op.f('fk_annotationtherapist_annotationschema_id_therapist_annotation_schema_therapist_annotation_schema'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotationtherapist_annotationschema')
    # ### end Alembic commands ###
