"""self-referencing table for client annotation labels

Revision ID: 1ef00b5d0961
Revises: 14ef024f9b6c
Create Date: 2023-10-16 17:49:38.351260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef00b5d0961'
down_revision = '14ef024f9b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['client_label.id'], name=op.f('fk_client_label_parent_id_client_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_label')),
    sa.UniqueConstraint('label', 'parent_id', name=op.f('uq_client_label_label'))
    )
    with op.batch_alter_table('client_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_label_label'), ['label'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_label_label'))

    op.drop_table('client_label')
    # ### end Alembic commands ###
