"""sm replies table

Revision ID: 1efa96495a18
Revises: baf164d26206
Create Date: 2023-05-22 14:10:12.075666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efa96495a18'
down_revision = 'baf164d26206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sm_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ldate', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id_sm_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_sm_post'], ['sm_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sm_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sm_reply_reply_id'), ['reply_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sm_reply_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sm_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sm_reply_user_id'))
        batch_op.drop_index(batch_op.f('ix_sm_reply_reply_id'))

    op.drop_table('sm_reply')
    # ### end Alembic commands ###
