"""separate label_e columns for client and therapist

Revision ID: 1f1c42386174
Revises: 0708a4d6a80d
Create Date: 2023-09-07 11:02:42.693766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1c42386174'
down_revision = '0708a4d6a80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_e_client', sa.Enum('insight', name='sublabelseclient'), nullable=True))
        batch_op.add_column(sa.Column('label_e_therapist', sa.Enum('general_helpfulness', name='sublabelsetherapist'), nullable=True))
        batch_op.drop_column('label_e')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_e', sa.VARCHAR(length=9), nullable=True))
        batch_op.drop_column('label_e_therapist')
        batch_op.drop_column('label_e_client')

    # ### end Alembic commands ###
