"""include moment of change for the client

Revision ID: 206d5e3d9b1d
Revises: c5d203a5ac98
Create Date: 2023-09-13 13:47:39.741183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "206d5e3d9b1d"
down_revision = "c5d203a5ac98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_f_client",
                sa.Enum("no_change", "switch", "escalation", name="sublabelsfclient"),
                nullable=True,
                default="no_change",
            )
        )
        batch_op.add_column(
            sa.Column(
                "strength_f_client",
                sa.Enum(
                    "significant_deterioration",
                    "some_deterioration",
                    "no_change",
                    "some_improvement",
                    "significant_improvement",
                    name="labelstrengthfclient",
                ),
                nullable=True,
                default="no_change",
            )
        )
        batch_op.add_column(sa.Column("comment_f", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.drop_column("comment_f")
        batch_op.drop_column("strength_f_client")
        batch_op.drop_column("label_f_client")

    # ### end Alembic commands ###
