"""separeta label_a columns for client and therapist

Revision ID: 21a172c36ac5
Revises: d06f3814442c
Create Date: 2023-09-05 13:04:24.506958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21a172c36ac5"
down_revision = "d06f3814442c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_a_client",
                sa.Enum(
                    "attachment",
                    "identity",
                    "security",
                    "excitement",
                    "other",
                    name="sublabelsaclient",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "label_a_therapist",
                sa.Enum(
                    "emotional",
                    "cognitive",
                    "respect",
                    "calming",
                    "other",
                    name="sublabelsatherapist",
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("label_a")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_a",
                sa.Enum(
                    "attachment",
                    "identity",
                    "security",
                    "excitement",
                    "other",
                    name="sublabelsa",
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("label_a_client")
        batch_op.drop_column("label_a_therapist")

    # ### end Alembic commands ###
