"""rename psychotherapy table

Revision ID: 220e96ed47d2
Revises: c000a6eeb3ac
Create Date: 2023-07-03 13:47:03.957923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220e96ed47d2'
down_revision = 'c000a6eeb3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_dialog_turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_text', sa.Text(), nullable=True),
    sa.Column('event_speaker', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('t_init', sa.String(length=64), nullable=True),
    sa.Column('c_code', sa.String(length=64), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_dialog_turn_id_dataset_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_dialog_turn'))
    )
    with op.batch_alter_table('ps_dialog_turn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ps_dialog_turn_c_code'), ['c_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ps_dialog_turn_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ps_dialog_turn_t_init'), ['t_init'], unique=False)

    with op.batch_alter_table('psychotherapy', schema=None) as batch_op:
        batch_op.drop_index('ix_psychotherapy_c_code')
        batch_op.drop_index('ix_psychotherapy_event_id')
        batch_op.drop_index('ix_psychotherapy_t_init')

    op.drop_table('psychotherapy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychotherapy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('event_text', sa.TEXT(), nullable=True),
    sa.Column('event_speaker', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('t_init', sa.VARCHAR(length=64), nullable=True),
    sa.Column('c_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id_dataset', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name='fk_psychotherapy_id_dataset_dataset'),
    sa.PrimaryKeyConstraint('id', name='pk_psychotherapy')
    )
    with op.batch_alter_table('psychotherapy', schema=None) as batch_op:
        batch_op.create_index('ix_psychotherapy_t_init', ['t_init'], unique=False)
        batch_op.create_index('ix_psychotherapy_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_psychotherapy_c_code', ['c_code'], unique=False)

    with op.batch_alter_table('ps_dialog_turn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_dialog_turn_t_init'))
        batch_op.drop_index(batch_op.f('ix_ps_dialog_turn_event_id'))
        batch_op.drop_index(batch_op.f('ix_ps_dialog_turn_c_code'))

    op.drop_table('ps_dialog_turn')
    # ### end Alembic commands ###
