"""rename psy client annotations table

Revision ID: 2a1e3a2c9238
Revises: 2df180d7b7c5
Create Date: 2023-09-26 14:30:42.983877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1e3a2c9238'
down_revision = '2df180d7b7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_annotation_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('label_a', sa.Enum('attachment', 'identity', 'security', 'excitement', 'other', name='sublabelsaclient'), nullable=True),
    sa.Column('label_b', sa.Enum('attachment', 'identity', 'security', 'excitement', 'other', name='sublabelsbclient'), nullable=True),
    sa.Column('label_c', sa.Enum('acceptance', 'esteem', 'fight', 'flight', 'other', name='sublabelscclient'), nullable=True),
    sa.Column('label_d', sa.Enum('hard_negative', 'soft_negative', 'neutral', 'positive', name='sublabelsdclient'), nullable=True),
    sa.Column('label_e', sa.Enum('insight', name='sublabelseclient'), nullable=True),
    sa.Column('label_f', sa.Enum('no_change', 'switch', 'escalation', name='sublabelsfclient'), nullable=True),
    sa.Column('strength_a', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthaclient'), nullable=True),
    sa.Column('strength_b', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthbclient'), nullable=True),
    sa.Column('strength_c', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthcclient'), nullable=True),
    sa.Column('strength_d', sa.Enum('highly_maladaptive', 'very_maladaptive', 'moderately_adaptive', 'very_adaptive', 'highly_adaptive', name='labelstrengthdclient'), nullable=True),
    sa.Column('strength_e', sa.Enum('no_recognition', 'low_recognition', 'moderate_recognition', 'good_recognition', 'excellent_recognition', name='labelstrengtheclient'), nullable=True),
    sa.Column('strength_f', sa.Enum('significant_deterioration', 'some_deterioration', 'no_change', 'some_improvement', 'significant_improvement', name='labelstrengthfclient'), nullable=True),
    sa.Column('comment_a', sa.Text(), nullable=True),
    sa.Column('comment_b', sa.Text(), nullable=True),
    sa.Column('comment_c', sa.Text(), nullable=True),
    sa.Column('comment_d', sa.Text(), nullable=True),
    sa.Column('comment_e', sa.Text(), nullable=True),
    sa.Column('comment_f', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_annotation_client_id_dataset_dataset')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_ps_annotation_client_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_annotation_client'))
    )
    with op.batch_alter_table('ps_annotation_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ps_annotation_client_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('ps_dialog_turn_annotation_client', schema=None) as batch_op:
        batch_op.drop_index('ix_ps_dialog_turn_annotation_client_timestamp')

    with op.batch_alter_table('annotationclient_dialogturn', schema=None) as batch_op:
        batch_op.drop_constraint('fk_annotationclient_dialogturn_id_annotation_client_ps_dialog_turn_annotation_client', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationclient_dialogturn_id_annotation_client_ps_annotation_client'), 'ps_annotation_client', ['id_annotation_client'], ['id'])

    op.drop_table('ps_dialog_turn_annotation_client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotationclient_dialogturn', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_annotationclient_dialogturn_id_annotation_client_ps_annotation_client'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationclient_dialogturn_id_annotation_client_ps_dialog_turn_annotation_client', 'ps_dialog_turn_annotation_client', ['id_annotation_client'], ['id'])

    op.create_table('ps_dialog_turn_annotation_client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('label_a', sa.VARCHAR(length=10), nullable=True),
    sa.Column('label_b', sa.VARCHAR(length=10), nullable=True),
    sa.Column('label_c', sa.VARCHAR(length=10), nullable=True),
    sa.Column('label_d', sa.VARCHAR(length=13), nullable=True),
    sa.Column('label_e', sa.VARCHAR(length=7), nullable=True),
    sa.Column('label_f', sa.VARCHAR(length=10), nullable=True),
    sa.Column('strength_a', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_b', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_c', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_d', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_e', sa.VARCHAR(length=21), nullable=True),
    sa.Column('strength_f', sa.VARCHAR(length=25), nullable=True),
    sa.Column('comment_a', sa.TEXT(), nullable=True),
    sa.Column('comment_b', sa.TEXT(), nullable=True),
    sa.Column('comment_c', sa.TEXT(), nullable=True),
    sa.Column('comment_d', sa.TEXT(), nullable=True),
    sa.Column('comment_e', sa.TEXT(), nullable=True),
    sa.Column('comment_f', sa.TEXT(), nullable=True),
    sa.Column('comment_summary', sa.TEXT(), nullable=True),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.Column('id_dataset', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name='fk_ps_dialog_turn_annotation_client_id_dataset_dataset'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='fk_ps_dialog_turn_annotation_client_id_user_user'),
    sa.PrimaryKeyConstraint('id', name='pk_ps_dialog_turn_annotation_client')
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_client', schema=None) as batch_op:
        batch_op.create_index('ix_ps_dialog_turn_annotation_client_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('ps_annotation_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_annotation_client_timestamp'))

    op.drop_table('ps_annotation_client')
    # ### end Alembic commands ###
