"""new table to store evidence for therapist annotations

Revision ID: 2cdbb94227e2
Revises: 691476e11756
Create Date: 2023-09-27 17:56:43.644459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdbb94227e2'
down_revision = '691476e11756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_therapist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_dialog_event', sa.Integer(), nullable=True),
    sa.Column('id_ps_annotation_therapist', sa.Integer(), nullable=True),
    sa.Column('label', sa.Enum('label_a', 'label_b', 'label_c', 'label_d', 'label_e', name='labelnamestherapist'), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name=op.f('fk_evidence_therapist_id_ps_annotation_therapist_ps_annotation_therapist')),
    sa.ForeignKeyConstraint(['id_ps_dialog_event'], ['ps_dialog_event.id'], name=op.f('fk_evidence_therapist_id_ps_dialog_event_ps_dialog_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_therapist'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_therapist')
    # ### end Alembic commands ###
