"""many-to-many relationship between dyad annotations and dialog turns

Revision ID: 2df180d7b7c5
Revises: 05243b011f6e
Create Date: 2023-09-25 15:51:55.205840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df180d7b7c5'
down_revision = '05243b011f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationsdyad_dialogturn',
    sa.Column('id_dialog_turn', sa.Integer(), nullable=True),
    sa.Column('id_annotation_dyad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_annotation_dyad'], ['ps_dialog_turn_annotation_dyad.id'], name=op.f('fk_annotationsdyad_dialogturn_id_annotation_dyad_ps_dialog_turn_annotation_dyad')),
    sa.ForeignKeyConstraint(['id_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_annotationsdyad_dialogturn_id_dialog_turn_ps_dialog_turn'))
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_dyad', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ps_dialog_turn_annotation_dyad_id_ps_dialog_turn_ps_dialog_turn', type_='foreignkey')
        batch_op.drop_column('id_ps_dialog_turn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation_dyad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ps_dialog_turn', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_ps_dialog_turn_annotation_dyad_id_ps_dialog_turn_ps_dialog_turn', 'ps_dialog_turn', ['id_ps_dialog_turn'], ['id'])

    op.drop_table('annotationsdyad_dialogturn')
    # ### end Alembic commands ###
