"""create foreign key between user and dataset tables

Revision ID: 2ed77c795197
Revises: aa8127ead755
Create Date: 2023-05-30 10:45:58.956951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed77c795197'
down_revision = 'aa8127ead755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_dataset_username')
        batch_op.create_foreign_key(batch_op.f('fk_dataset_id_user_user'), 'user', ['id_user'], ['id'])
        batch_op.drop_column('timesaved')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('timesaved', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_dataset_id_user_user'), type_='foreignkey')
        batch_op.create_index('ix_dataset_username', ['username'], unique=False)
        batch_op.drop_column('id_user')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
