"""table for therapist annotation schema scales

Revision ID: 2fd79c36ebbc
Revises: 6024d2f7a78f
Create Date: 2023-10-25 17:31:54.941424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd79c36ebbc'
down_revision = '6024d2f7a78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_annotation_schema_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_title', sa.String(length=64), nullable=False),
    sa.Column('scale_level', sa.String(length=64), nullable=False),
    sa.Column('id_therapist_annotation_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_therapist_annotation_schema'], ['therapist_annotation_schema.id'], name=op.f('fk_therapist_annotation_schema_scale_id_therapist_annotation_schema_therapist_annotation_schema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapist_annotation_schema_scale')),
    sa.UniqueConstraint('scale_title', 'id_therapist_annotation_schema', name=op.f('uq_therapist_annotation_schema_scale_scale_title'))
    )
    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapist_annotation_schema_scale_scale_level'), ['scale_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_therapist_annotation_schema_scale_scale_title'), ['scale_title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapist_annotation_schema_scale_scale_title'))
        batch_op.drop_index(batch_op.f('ix_therapist_annotation_schema_scale_scale_level'))

    op.drop_table('therapist_annotation_schema_scale')
    # ### end Alembic commands ###
