"""rename table to store therapist annotation scales

Revision ID: 358f46e37a0c
Revises: 01c3de2250fd
Create Date: 2023-12-11 16:22:59.317570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358f46e37a0c'
down_revision = '01c3de2250fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_annotation_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_title', sa.String(length=64), nullable=False),
    sa.Column('scale_level', sa.String(length=64), nullable=False),
    sa.Column('id_therapist_annotation_label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_therapist_annotation_label'], ['therapist_annotation_label.id'], name=op.f('fk_therapist_annotation_scale_id_therapist_annotation_label_therapist_annotation_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapist_annotation_scale')),
    sa.UniqueConstraint('scale_title', 'scale_level', 'id_therapist_annotation_label', name=op.f('uq_therapist_annotation_scale_scale_title'))
    )
    with op.batch_alter_table('therapist_annotation_scale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapist_annotation_scale_scale_level'), ['scale_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_therapist_annotation_scale_scale_title'), ['scale_title'], unique=False)

    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_index('ix_therapist_annotation_schema_scale_scale_level')
        batch_op.drop_index('ix_therapist_annotation_schema_scale_scale_title')

    with op.batch_alter_table('annotationtherapist_annotationschemascale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_scale', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_annotationtherapist_annotationschemascale_id_therapist_annotation_schema_scale_therapist_annotation_schema_scale', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationtherapist_annotationschemascale_id_therapist_annotation_scale_therapist_annotation_scale'), 'therapist_annotation_scale', ['id_therapist_annotation_scale'], ['id'])
        batch_op.drop_column('id_therapist_annotation_schema_scale')

    op.drop_table('therapist_annotation_schema_scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotationtherapist_annotationschemascale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_schema_scale', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_annotationtherapist_annotationschemascale_id_therapist_annotation_scale_therapist_annotation_scale'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationtherapist_annotationschemascale_id_therapist_annotation_schema_scale_therapist_annotation_schema_scale', 'therapist_annotation_schema_scale', ['id_therapist_annotation_schema_scale'], ['id'])
        batch_op.drop_column('id_therapist_annotation_scale')

    op.create_table('therapist_annotation_schema_scale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_therapist_annotation_label', sa.INTEGER(), nullable=True),
    sa.Column('scale_title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('scale_level', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['id_therapist_annotation_label'], ['therapist_annotation_label.id'], name='fk_therapist_annotation_schema_scale_id_therapist_annotation_label_therapist_annotation_label'),
    sa.PrimaryKeyConstraint('id', name='pk_therapist_annotation_schema_scale'),
    sa.UniqueConstraint('scale_title', 'scale_level', 'id_therapist_annotation_label', name='uq_therapist_annotation_schema_scale_scale_title')
    )
    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.create_index('ix_therapist_annotation_schema_scale_scale_title', ['scale_title'], unique=False)
        batch_op.create_index('ix_therapist_annotation_schema_scale_scale_level', ['scale_level'], unique=False)

    with op.batch_alter_table('therapist_annotation_scale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapist_annotation_scale_scale_title'))
        batch_op.drop_index(batch_op.f('ix_therapist_annotation_scale_scale_level'))

    op.drop_table('therapist_annotation_scale')
    # ### end Alembic commands ###
