"""update annotations schema for dyad

Revision ID: 36b6fa8c1f32
Revises: a70163aecf8f
Create Date: 2023-10-17 16:53:23.823117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b6fa8c1f32'
down_revision = 'a70163aecf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dyad_annotation_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dyad_annotation_schema.id'], name=op.f('fk_dyad_annotation_schema_parent_id_dyad_annotation_schema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dyad_annotation_schema')),
    sa.UniqueConstraint('label', 'parent_id', name=op.f('uq_dyad_annotation_schema_label'))
    )
    with op.batch_alter_table('dyad_annotation_schema', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dyad_annotation_schema_label'), ['label'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dyad_annotation_schema', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dyad_annotation_schema_label'))

    op.drop_table('dyad_annotation_schema')
    # ### end Alembic commands ###
