"""table to store annotation comments for therapist

Revision ID: 3954c5c59575
Revises: 45fd6f42a880
Create Date: 2023-11-29 17:21:08.038710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3954c5c59575'
down_revision = '45fd6f42a880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_annotation_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id_therapist_annotation_schema', sa.Integer(), nullable=True),
    sa.Column('id_ps_annotation_therapist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name=op.f('fk_therapist_annotation_comment_id_ps_annotation_therapist_ps_annotation_therapist')),
    sa.ForeignKeyConstraint(['id_therapist_annotation_schema'], ['therapist_annotation_schema.id'], name=op.f('fk_therapist_annotation_comment_id_therapist_annotation_schema_therapist_annotation_schema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapist_annotation_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapist_annotation_comment')
    # ### end Alembic commands ###
