"""update table to store dyad annotations

Revision ID: 3a72b32963cf
Revises: 3c263e4c8c7b
Create Date: 2023-11-30 17:21:51.004866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72b32963cf'
down_revision = '3c263e4c8c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationdyad_annotationschemascale',
    sa.Column('id_ps_annotation_dyad', sa.Integer(), nullable=True),
    sa.Column('id_dyad_annotation_schema_scale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_schema_scale'], ['dyad_annotation_schema_scale.id'], name=op.f('fk_annotationdyad_annotationschemascale_id_dyad_annotation_schema_scale_dyad_annotation_schema_scale')),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name=op.f('fk_annotationdyad_annotationschemascale_id_ps_annotation_dyad_ps_annotation_dyad'))
    )
    with op.batch_alter_table('ps_annotation_dyad', schema=None) as batch_op:
        batch_op.drop_column('comment_a')
        batch_op.drop_column('label_b')
        batch_op.drop_column('strength_b')
        batch_op.drop_column('comment_b')
        batch_op.drop_column('label_a')
        batch_op.drop_column('strength_a')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_annotation_dyad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_a', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('label_a', sa.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('comment_b', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('strength_b', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('label_b', sa.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('comment_a', sa.TEXT(), nullable=True))

    op.drop_table('annotationdyad_annotationschemascale')
    # ### end Alembic commands ###
