"""association table between client annotations and scales

Revision ID: 3b6adc698c71
Revises: 74de3d6a9171
Create Date: 2023-10-31 15:31:24.216938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6adc698c71'
down_revision = '74de3d6a9171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationclient_annotationschemascale',
    sa.Column('id_ps_annotation_client', sa.Integer(), nullable=True),
    sa.Column('id_client_annotation_schema_scale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_schema_scale'], ['client_annotation_schema_scale.id'], name=op.f('fk_annotationclient_annotationschemascale_id_client_annotation_schema_scale_client_annotation_schema_scale')),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name=op.f('fk_annotationclient_annotationschemascale_id_ps_annotation_client_ps_annotation_client'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotationclient_annotationschemascale')
    # ### end Alembic commands ###
