"""table for dyad annotation comments

Revision ID: 3c263e4c8c7b
Revises: c99c9c8ababb
Create Date: 2023-11-30 16:40:01.491072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c263e4c8c7b'
down_revision = 'c99c9c8ababb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dyad_annotation_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id_dyad_annotation_schema', sa.Integer(), nullable=True),
    sa.Column('id_ps_annotation_dyad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_schema'], ['dyad_annotation_schema.id'], name=op.f('fk_dyad_annotation_comment_id_dyad_annotation_schema_dyad_annotation_schema')),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name=op.f('fk_dyad_annotation_comment_id_ps_annotation_dyad_ps_annotation_dyad')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dyad_annotation_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dyad_annotation_comment')
    # ### end Alembic commands ###
