"""add columns for dyad to annotations table

Revision ID: 3e2a87f8c515
Revises: e90ac647b9d6
Create Date: 2023-09-10 18:42:27.414056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2a87f8c515'
down_revision = 'e90ac647b9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_a_dyad', sa.Enum('bond', 'tasks_goals', name='sublabelsadyad'), nullable=True))
        batch_op.add_column(sa.Column('label_b_dyad', sa.Enum('confrontational', 'withdrawal', 'other', name='sublabelsbdyad'), nullable=True))
        batch_op.add_column(sa.Column('strength_a_dyad', sa.Enum('low', 'medium', 'high', name='labelstrengthadyad'), nullable=True))
        batch_op.add_column(sa.Column('strength_b_dyad', sa.Enum('high', 'medium', 'low', name='labelstrengthbdyad'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_column('strength_b_dyad')
        batch_op.drop_column('strength_a_dyad')
        batch_op.drop_column('label_b_dyad')
        batch_op.drop_column('label_a_dyad')

    # ### end Alembic commands ###
