"""association table between therapist annotations and schema scale table

Revision ID: 45fd6f42a880
Revises: 64ddad024e59
Create Date: 2023-11-29 17:12:48.893423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fd6f42a880'
down_revision = '64ddad024e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationtherapist_annotationschemascale',
    sa.Column('id_ps_annotation_therapist', sa.Integer(), nullable=True),
    sa.Column('id_therapist_annotation_schema_scale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name=op.f('fk_annotationtherapist_annotationschemascale_id_ps_annotation_therapist_ps_annotation_therapist')),
    sa.ForeignKeyConstraint(['id_therapist_annotation_schema_scale'], ['therapist_annotation_schema_scale.id'], name=op.f('fk_annotationtherapist_annotationschemascale_id_therapist_annotation_schema_scale_therapist_annotation_schema_scale'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotationtherapist_annotationschemascale')
    # ### end Alembic commands ###
