"""many-to-many relationship between client annotations and dialog turns

Revision ID: 4fa61cab1a99
Revises: 0a2130aa229e
Create Date: 2023-09-25 12:17:01.483948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa61cab1a99'
down_revision = '0a2130aa229e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationclient_dialogturn',
    sa.Column('id_dialog_turn', sa.Integer(), nullable=True),
    sa.Column('id_annotation_client', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_annotation_client'], ['ps_dialog_turn_annotation_client.id'], name=op.f('fk_annotationclient_dialogturn_id_annotation_client_ps_dialog_turn_annotation_client')),
    sa.ForeignKeyConstraint(['id_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_annotationclient_dialogturn_id_dialog_turn_ps_dialog_turn'))
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_client', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ps_dialog_turn_annotation_client_id_ps_dialog_turn_ps_dialog_turn', type_='foreignkey')
        batch_op.drop_column('id_ps_dialog_turn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ps_dialog_turn', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_ps_dialog_turn_annotation_client_id_ps_dialog_turn_ps_dialog_turn', 'ps_dialog_turn', ['id_ps_dialog_turn'], ['id'])

    op.drop_table('annotationclient_dialogturn')
    # ### end Alembic commands ###
