"""separate label_c columns for client and therapist

Revision ID: 5bd1ea5df646
Revises: 712f4551c351
Create Date: 2023-09-06 15:28:47.491578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5bd1ea5df646"
down_revision = "712f4551c351"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_c_client",
                sa.Enum(
                    "acceptance",
                    "esteem",
                    "fight",
                    "flight",
                    "other",
                    name="sublabelscclient",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "label_c_therapist",
                sa.Enum(
                    "questions",
                    "exploration",
                    "upregulation",
                    "other",
                    name="sublabelsctherapist",
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("label_c")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_c",
                sa.Enum(
                    "sublabel1",
                    "sublabel2",
                    "sublabel3",
                    "sublabel4",
                    "other",
                    name="sublabelsc",
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("label_c_therapist")
        batch_op.drop_column("label_c_client")

    # ### end Alembic commands ###
