"""create strength labels A to D for the client

Revision ID: 5d505fe12656
Revises: 1f1c42386174
Create Date: 2023-09-07 14:38:28.466224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d505fe12656'
down_revision = '1f1c42386174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_a_client', sa.Enum('strength1', 'strength2', 'strength3', 'strength4', 'strength5', name='labelstrengthaclient'), nullable=True))
        batch_op.add_column(sa.Column('strength_b_client', sa.Enum('strength1', 'strength2', 'strength3', 'strength4', 'strength5', name='labelstrengthbclient'), nullable=True))
        batch_op.add_column(sa.Column('strength_c_client', sa.Enum('strength1', 'strength2', 'strength3', 'strength4', 'strength5', name='labelstrengthcclient'), nullable=True))
        batch_op.add_column(sa.Column('strength_d_client', sa.Enum('strength1', 'strength2', 'strength3', 'strength4', 'strength5', name='labelstrengthdclient'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_column('strength_d_client')
        batch_op.drop_column('strength_c_client')
        batch_op.drop_column('strength_b_client')
        batch_op.drop_column('strength_a_client')

    # ### end Alembic commands ###
