"""table for client annotation schema scales

Revision ID: 6024d2f7a78f
Revises: 6cc8ffb4f00f
Create Date: 2023-10-25 17:04:51.255725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6024d2f7a78f'
down_revision = '6cc8ffb4f00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_annotation_schema_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_title', sa.String(length=64), nullable=False),
    sa.Column('scale_level', sa.String(length=64), nullable=False),
    sa.Column('id_client_annotation_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_schema'], ['client_annotation_schema.id'], name=op.f('fk_client_annotation_schema_scale_id_client_annotation_schema_client_annotation_schema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_annotation_schema_scale')),
    sa.UniqueConstraint('scale_title', 'id_client_annotation_schema', name=op.f('uq_client_annotation_schema_scale_scale_title'))
    )
    with op.batch_alter_table('client_annotation_schema_scale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_annotation_schema_scale_scale_level'), ['scale_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_annotation_schema_scale_scale_title'), ['scale_title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_annotation_schema_scale_scale_title'))
        batch_op.drop_index(batch_op.f('ix_client_annotation_schema_scale_scale_level'))

    op.drop_table('client_annotation_schema_scale')
    # ### end Alembic commands ###
