"""table to store client annotation comments

Revision ID: 64ddad024e59
Revises: 3b6adc698c71
Create Date: 2023-10-31 16:09:18.265693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ddad024e59'
down_revision = '3b6adc698c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_annotation_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id_client_annotation_schema', sa.Integer(), nullable=True),
    sa.Column('id_ps_annotation_client', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_schema'], ['client_annotation_schema.id'], name=op.f('fk_client_annotation_comment_id_client_annotation_schema_client_annotation_schema')),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name=op.f('fk_client_annotation_comment_id_ps_annotation_client_ps_annotation_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_annotation_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_annotation_comment')
    # ### end Alembic commands ###
