"""rename table to store client annotation scales

Revision ID: 6600f656b065
Revises: fd4804e93b31
Create Date: 2023-12-08 18:07:18.385638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6600f656b065'
down_revision = 'fd4804e93b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_annotation_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_title', sa.String(length=64), nullable=False),
    sa.Column('scale_level', sa.String(length=64), nullable=False),
    sa.Column('id_client_annotation_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_schema'], ['client_annotation_schema.id'], name=op.f('fk_client_annotation_scale_id_client_annotation_schema_client_annotation_schema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_annotation_scale')),
    sa.UniqueConstraint('scale_title', 'scale_level', 'id_client_annotation_schema', name=op.f('uq_client_annotation_scale_scale_title'))
    )
    with op.batch_alter_table('client_annotation_scale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_annotation_scale_scale_level'), ['scale_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_annotation_scale_scale_title'), ['scale_title'], unique=False)

    with op.batch_alter_table('client_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_index('ix_client_annotation_schema_scale_scale_level')
        batch_op.drop_index('ix_client_annotation_schema_scale_scale_title')

    with op.batch_alter_table('annotationclient_annotationschemascale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_scale', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_annotationclient_annotationschemascale_id_client_annotation_schema_scale_client_annotation_schema_scale', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationclient_annotationschemascale_id_client_annotation_scale_client_annotation_scale'), 'client_annotation_scale', ['id_client_annotation_scale'], ['id'])
        batch_op.drop_column('id_client_annotation_schema_scale')

    op.drop_table('client_annotation_schema_scale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotationclient_annotationschemascale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_schema_scale', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_annotationclient_annotationschemascale_id_client_annotation_scale_client_annotation_scale'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationclient_annotationschemascale_id_client_annotation_schema_scale_client_annotation_schema_scale', 'client_annotation_schema_scale', ['id_client_annotation_schema_scale'], ['id'])
        batch_op.drop_column('id_client_annotation_scale')

    op.create_table('client_annotation_schema_scale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scale_title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('scale_level', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id_client_annotation_schema', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_schema'], ['client_annotation_schema.id'], name='fk_client_annotation_schema_scale_id_client_annotation_schema_client_annotation_schema'),
    sa.PrimaryKeyConstraint('id', name='pk_client_annotation_schema_scale'),
    sa.UniqueConstraint('scale_title', 'scale_level', 'id_client_annotation_schema', name='uq_client_annotation_schema_scale_scale_title')
    )
    with op.batch_alter_table('client_annotation_schema_scale', schema=None) as batch_op:
        batch_op.create_index('ix_client_annotation_schema_scale_scale_title', ['scale_title'], unique=False)
        batch_op.create_index('ix_client_annotation_schema_scale_scale_level', ['scale_level'], unique=False)

    with op.batch_alter_table('client_annotation_scale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_annotation_scale_scale_title'))
        batch_op.drop_index(batch_op.f('ix_client_annotation_scale_scale_level'))

    op.drop_table('client_annotation_scale')
    # ### end Alembic commands ###
