"""rename table to store therapist annotation labels

Revision ID: 68dbe8b2459d
Revises: b1ef06d88844
Create Date: 2023-12-11 14:44:29.871494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dbe8b2459d'
down_revision = 'b1ef06d88844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_annotation_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['therapist_annotation_label.id'], name=op.f('fk_therapist_annotation_label_parent_id_therapist_annotation_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapist_annotation_label')),
    sa.UniqueConstraint('label', 'parent_id', name=op.f('uq_therapist_annotation_label_label'))
    )
    with op.batch_alter_table('therapist_annotation_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapist_annotation_label_label'), ['label'], unique=False)

    with op.batch_alter_table('therapist_annotation_schema', schema=None) as batch_op:
        batch_op.drop_index('ix_therapist_annotation_schema_label')

    with op.batch_alter_table('annotationtherapist_annotationschema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_label', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_annotationtherapist_annotationschema_id_therapist_annotation_schema_therapist_annotation_schema', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationtherapist_annotationschema_id_therapist_annotation_label_therapist_annotation_label'), 'therapist_annotation_label', ['id_therapist_annotation_label'], ['id'])
        batch_op.drop_column('id_therapist_annotation_schema')

    with op.batch_alter_table('therapist_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_label', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_therapist_annotation_comment_id_therapist_annotation_schema_therapist_annotation_schema', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_therapist_annotation_comment_id_therapist_annotation_label_therapist_annotation_label'), 'therapist_annotation_label', ['id_therapist_annotation_label'], ['id'])
        batch_op.drop_column('id_therapist_annotation_schema')

    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_label', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_therapist_annotation_schema_scale_scale_title', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_therapist_annotation_schema_scale_scale_title'), ['scale_title', 'scale_level', 'id_therapist_annotation_label'])
        batch_op.drop_constraint('fk_therapist_annotation_schema_scale_id_therapist_annotation_schema_therapist_annotation_schema', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_therapist_annotation_schema_scale_id_therapist_annotation_label_therapist_annotation_label'), 'therapist_annotation_label', ['id_therapist_annotation_label'], ['id'])
        batch_op.drop_column('id_therapist_annotation_schema')

    op.drop_table('therapist_annotation_schema')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_schema', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_therapist_annotation_schema_scale_id_therapist_annotation_label_therapist_annotation_label'), type_='foreignkey')
        batch_op.create_foreign_key('fk_therapist_annotation_schema_scale_id_therapist_annotation_schema_therapist_annotation_schema', 'therapist_annotation_schema', ['id_therapist_annotation_schema'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_therapist_annotation_schema_scale_scale_title'), type_='unique')
        batch_op.create_unique_constraint('uq_therapist_annotation_schema_scale_scale_title', ['scale_title', 'scale_level', 'id_therapist_annotation_schema'])
        batch_op.drop_column('id_therapist_annotation_label')

    with op.batch_alter_table('therapist_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_schema', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_therapist_annotation_comment_id_therapist_annotation_label_therapist_annotation_label'), type_='foreignkey')
        batch_op.create_foreign_key('fk_therapist_annotation_comment_id_therapist_annotation_schema_therapist_annotation_schema', 'therapist_annotation_schema', ['id_therapist_annotation_schema'], ['id'])
        batch_op.drop_column('id_therapist_annotation_label')

    with op.batch_alter_table('annotationtherapist_annotationschema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_schema', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_annotationtherapist_annotationschema_id_therapist_annotation_label_therapist_annotation_label'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationtherapist_annotationschema_id_therapist_annotation_schema_therapist_annotation_schema', 'therapist_annotation_schema', ['id_therapist_annotation_schema'], ['id'])
        batch_op.drop_column('id_therapist_annotation_label')

    op.create_table('therapist_annotation_schema',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['therapist_annotation_schema.id'], name='fk_therapist_annotation_schema_parent_id_therapist_annotation_schema'),
    sa.PrimaryKeyConstraint('id', name='pk_therapist_annotation_schema'),
    sa.UniqueConstraint('label', 'parent_id', name='uq_therapist_annotation_schema_label')
    )
    with op.batch_alter_table('therapist_annotation_schema', schema=None) as batch_op:
        batch_op.create_index('ix_therapist_annotation_schema_label', ['label'], unique=False)

    with op.batch_alter_table('therapist_annotation_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_therapist_annotation_label_label'))

    op.drop_table('therapist_annotation_label')
    # ### end Alembic commands ###
