"""new table to store evidence for client annotations

Revision ID: 691476e11756
Revises: f77d253b05cc
Create Date: 2023-09-26 16:47:52.522232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691476e11756'
down_revision = 'f77d253b05cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_dialog_event', sa.Integer(), nullable=True),
    sa.Column('id_ps_annotation_client', sa.Integer(), nullable=True),
    sa.Column('label', sa.Enum('label_a', 'label_b', 'label_c', 'label_d', 'label_e', 'label_f', name='labelnamesclient'), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name=op.f('fk_evidence_client_id_ps_annotation_client_ps_annotation_client')),
    sa.ForeignKeyConstraint(['id_ps_dialog_event'], ['ps_dialog_event.id'], name=op.f('fk_evidence_client_id_ps_dialog_event_ps_dialog_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_client'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_client')
    # ### end Alembic commands ###
