"""drop unused strength columns

Revision ID: 6a48bc97cce5
Revises: baee7d5abf5e
Create Date: 2023-09-07 15:29:30.688218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a48bc97cce5'
down_revision = 'baee7d5abf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_column('strength_b')
        batch_op.drop_column('strength_d')
        batch_op.drop_column('strength_e')
        batch_op.drop_column('strength_a')
        batch_op.drop_column('strength_c')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_c', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('strength_a', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('strength_e', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('strength_d', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('strength_b', sa.VARCHAR(length=6), nullable=True))

    # ### end Alembic commands ###
