"""association table between annotations and schema for dyad

Revision ID: 6cc8ffb4f00f
Revises: 189cf70c7b8b
Create Date: 2023-10-25 11:19:03.100941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc8ffb4f00f'
down_revision = '189cf70c7b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationdyad_annotationschema',
    sa.Column('id_ps_annotation_dyad', sa.Integer(), nullable=True),
    sa.Column('id_dyad_annotation_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_schema'], ['dyad_annotation_schema.id'], name=op.f('fk_annotationdyad_annotationschema_id_dyad_annotation_schema_dyad_annotation_schema')),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name=op.f('fk_annotationdyad_annotationschema_id_ps_annotation_dyad_ps_annotation_dyad'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotationdyad_annotationschema')
    # ### end Alembic commands ###
