"""update table to store therapist annotation comments

Revision ID: 6e93ea750132
Revises: 759f9c7593ea
Create Date: 2023-12-12 14:09:15.429558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e93ea750132'
down_revision = '759f9c7593ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_additional', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist_annotation_comment', schema=None) as batch_op:
        batch_op.drop_column('is_additional')

    # ### end Alembic commands ###
