"""replace association table with association object for annotation-scales

Revision ID: 700345962f8e
Revises: 6600f656b065
Create Date: 2023-12-08 18:33:06.384563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700345962f8e'
down_revision = '6600f656b065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationclient_annotationscale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_annotation_client', sa.Integer(), nullable=False),
    sa.Column('id_client_annotation_scale', sa.Integer(), nullable=False),
    sa.Column('is_additional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_scale'], ['client_annotation_scale.id'], name=op.f('fk_annotationclient_annotationscale_id_client_annotation_scale_client_annotation_scale')),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name=op.f('fk_annotationclient_annotationscale_id_ps_annotation_client_ps_annotation_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotationclient_annotationscale'))
    )
    op.drop_table('annotationclient_annotationschemascale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationclient_annotationschemascale',
    sa.Column('id_ps_annotation_client', sa.INTEGER(), nullable=True),
    sa.Column('id_client_annotation_scale', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_scale'], ['client_annotation_scale.id'], name='fk_annotationclient_annotationschemascale_id_client_annotation_scale_client_annotation_scale'),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name='fk_annotationclient_annotationschemascale_id_ps_annotation_client_ps_annotation_client')
    )
    op.drop_table('annotationclient_annotationscale')
    # ### end Alembic commands ###
