"""separate label_b columns for client and therapist

Revision ID: 712f4551c351
Revises: 21a172c36ac5
Create Date: 2023-09-06 11:36:45.399972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "712f4551c351"
down_revision = "21a172c36ac5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_b_client",
                sa.Enum(
                    "attachment",
                    "identity",
                    "security",
                    "excitement",
                    "other",
                    name="sublabelsbclient",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "label_b_therapist",
                sa.Enum(
                    "interpretation",
                    "reframing",
                    "reflection",
                    "transference",
                    "other",
                    name="sublabelsbtherapist",
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("label_b")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_b",
                sa.Enum(
                    "sublabel1",
                    "sublabel2",
                    "sublabel3",
                    "sublabel4",
                    "other",
                    name="sublabelsb",
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("label_b_therapist")
        batch_op.drop_column("label_b_client")

    # ### end Alembic commands ###
