"""create strength labels A to E for the therapist

Revision ID: 718b65826dce
Revises: 5d505fe12656
Create Date: 2023-09-07 15:06:03.906409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718b65826dce'
down_revision = '5d505fe12656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_a_therapist', sa.Enum('low', 'medium', 'high', name='labelstrengthatherapist'), nullable=True))
        batch_op.add_column(sa.Column('strength_b_therapist', sa.Enum('low', 'medium', 'high', name='labelstrengthbtherapist'), nullable=True))
        batch_op.add_column(sa.Column('strength_c_therapist', sa.Enum('low', 'medium', 'high', name='labelstrengthctherapist'), nullable=True))
        batch_op.add_column(sa.Column('strength_d_therapist', sa.Enum('low', 'medium', 'high', name='labelstrengthdtherapist'), nullable=True))
        batch_op.add_column(sa.Column('strength_e_therapist', sa.Enum('low', 'medium', 'high', name='labelstrengthetherapist'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_column('strength_e_therapist')
        batch_op.drop_column('strength_d_therapist')
        batch_op.drop_column('strength_c_therapist')
        batch_op.drop_column('strength_b_therapist')
        batch_op.drop_column('strength_a_therapist')

    # ### end Alembic commands ###
