"""update client psy annotation table

Revision ID: 74de3d6a9171
Revises: d91305e2a856
Create Date: 2023-10-31 15:20:08.924118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74de3d6a9171'
down_revision = 'd91305e2a856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_annotation_client', schema=None) as batch_op:
        batch_op.drop_column('comment_d')
        batch_op.drop_column('label_e')
        batch_op.drop_column('label_d')
        batch_op.drop_column('strength_c')
        batch_op.drop_column('label_b')
        batch_op.drop_column('strength_f')
        batch_op.drop_column('comment_a')
        batch_op.drop_column('comment_c')
        batch_op.drop_column('strength_e')
        batch_op.drop_column('label_f')
        batch_op.drop_column('strength_b')
        batch_op.drop_column('comment_f')
        batch_op.drop_column('label_c')
        batch_op.drop_column('comment_b')
        batch_op.drop_column('strength_a')
        batch_op.drop_column('label_a')
        batch_op.drop_column('strength_d')
        batch_op.drop_column('comment_e')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_annotation_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_e', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('strength_d', sa.VARCHAR(length=19), nullable=True))
        batch_op.add_column(sa.Column('label_a', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('strength_a', sa.VARCHAR(length=19), nullable=True))
        batch_op.add_column(sa.Column('comment_b', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('label_c', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('comment_f', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('strength_b', sa.VARCHAR(length=19), nullable=True))
        batch_op.add_column(sa.Column('label_f', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('strength_e', sa.VARCHAR(length=21), nullable=True))
        batch_op.add_column(sa.Column('comment_c', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('comment_a', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('strength_f', sa.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('label_b', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('strength_c', sa.VARCHAR(length=19), nullable=True))
        batch_op.add_column(sa.Column('label_d', sa.VARCHAR(length=13), nullable=True))
        batch_op.add_column(sa.Column('label_e', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('comment_d', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
