"""update table to store therapist evidence events

Revision ID: 759f9c7593ea
Revises: a99bd2e6e098
Create Date: 2023-12-12 11:28:02.821376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759f9c7593ea'
down_revision = 'a99bd2e6e098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_therapist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_therapist_annotation_label', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_additional', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_evidence_therapist_id_therapist_annotation_label_therapist_annotation_label'), 'therapist_annotation_label', ['id_therapist_annotation_label'], ['id'])
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_therapist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=7), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_evidence_therapist_id_therapist_annotation_label_therapist_annotation_label'), type_='foreignkey')
        batch_op.drop_column('is_additional')
        batch_op.drop_column('id_therapist_annotation_label')

    # ### end Alembic commands ###
