"""further work in ps dialog turn annotations

Revision ID: 77807f9373ae
Revises: c610bdcfbe56
Create Date: 2023-07-13 12:08:54.629545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77807f9373ae'
down_revision = 'c610bdcfbe56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_a', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_b', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_d', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_e', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('speaker', sa.Enum('client', 'therapist', name='speaker'), nullable=True))
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ps_dialog_turn_annotation_id_user_user'), 'user', ['id_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ps_dialog_turn_annotation_id_user_user'), type_='foreignkey')
        batch_op.drop_column('id_user')
        batch_op.drop_column('speaker')
        batch_op.drop_column('comment_e')
        batch_op.drop_column('comment_d')
        batch_op.drop_column('comment_c')
        batch_op.drop_column('comment_b')
        batch_op.drop_column('comment_a')

    # ### end Alembic commands ###
