"""rename psy therapist annotations table

Revision ID: 87fe63ffa1a3
Revises: 2a1e3a2c9238
Create Date: 2023-09-26 14:55:21.451626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fe63ffa1a3'
down_revision = '2a1e3a2c9238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_annotation_therapist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('label_a', sa.Enum('emotional', 'cognitive', 'respect', 'calming', 'other', name='sublabelsatherapist'), nullable=True),
    sa.Column('label_b', sa.Enum('interpretation', 'reframing', 'reflection', 'transference', 'other', name='sublabelsbtherapist'), nullable=True),
    sa.Column('label_c', sa.Enum('questions', 'exploration', 'upregulation', 'other', name='sublabelsctherapist'), nullable=True),
    sa.Column('label_d', sa.Enum('restructuring', 'suggest_change', 'encouragement', 'advice', 'other', name='sublabelsdtherapist'), nullable=True),
    sa.Column('label_e', sa.Enum('general_helpfulness', name='sublabelsetherapist'), nullable=True),
    sa.Column('strength_a', sa.Enum('low', 'medium', 'high', name='labelstrengthatherapist'), nullable=True),
    sa.Column('strength_b', sa.Enum('low', 'medium', 'high', name='labelstrengthbtherapist'), nullable=True),
    sa.Column('strength_c', sa.Enum('low', 'medium', 'high', name='labelstrengthctherapist'), nullable=True),
    sa.Column('strength_d', sa.Enum('low', 'medium', 'high', name='labelstrengthdtherapist'), nullable=True),
    sa.Column('strength_e', sa.Enum('low', 'medium', 'high', name='labelstrengthetherapist'), nullable=True),
    sa.Column('comment_a', sa.Text(), nullable=True),
    sa.Column('comment_b', sa.Text(), nullable=True),
    sa.Column('comment_c', sa.Text(), nullable=True),
    sa.Column('comment_d', sa.Text(), nullable=True),
    sa.Column('comment_e', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_annotation_therapist_id_dataset_dataset')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_ps_annotation_therapist_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_annotation_therapist'))
    )
    with op.batch_alter_table('ps_annotation_therapist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ps_annotation_therapist_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('ps_dialog_turn_annotation_therapist', schema=None) as batch_op:
        batch_op.drop_index('ix_ps_dialog_turn_annotation_therapist_timestamp')

    with op.batch_alter_table('annotationtherapist_dialogturn', schema=None) as batch_op:
        batch_op.drop_constraint('fk_annotationtherapist_dialogturn_id_annotation_therapist_ps_dialog_turn_annotation_therapist', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationtherapist_dialogturn_id_annotation_therapist_ps_annotation_therapist'), 'ps_annotation_therapist', ['id_annotation_therapist'], ['id'])

    op.drop_table('ps_dialog_turn_annotation_therapist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotationtherapist_dialogturn', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_annotationtherapist_dialogturn_id_annotation_therapist_ps_annotation_therapist'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationtherapist_dialogturn_id_annotation_therapist_ps_dialog_turn_annotation_therapist', 'ps_dialog_turn_annotation_therapist', ['id_annotation_therapist'], ['id'])

    op.create_table('ps_dialog_turn_annotation_therapist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('label_a', sa.VARCHAR(length=9), nullable=True),
    sa.Column('label_b', sa.VARCHAR(length=14), nullable=True),
    sa.Column('label_c', sa.VARCHAR(length=12), nullable=True),
    sa.Column('label_d', sa.VARCHAR(length=14), nullable=True),
    sa.Column('label_e', sa.VARCHAR(length=19), nullable=True),
    sa.Column('strength_a', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_b', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_c', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_d', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_e', sa.VARCHAR(length=6), nullable=True),
    sa.Column('comment_a', sa.TEXT(), nullable=True),
    sa.Column('comment_b', sa.TEXT(), nullable=True),
    sa.Column('comment_c', sa.TEXT(), nullable=True),
    sa.Column('comment_d', sa.TEXT(), nullable=True),
    sa.Column('comment_e', sa.TEXT(), nullable=True),
    sa.Column('comment_summary', sa.TEXT(), nullable=True),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.Column('id_dataset', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name='fk_ps_dialog_turn_annotation_therapist_id_dataset_dataset'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='fk_ps_dialog_turn_annotation_therapist_id_user_user'),
    sa.PrimaryKeyConstraint('id', name='pk_ps_dialog_turn_annotation_therapist')
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_therapist', schema=None) as batch_op:
        batch_op.create_index('ix_ps_dialog_turn_annotation_therapist_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('ps_annotation_therapist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_annotation_therapist_timestamp'))

    op.drop_table('ps_annotation_therapist')
    # ### end Alembic commands ###