"""more foreign keys for psychotherapy

Revision ID: 8c2f6390dd52
Revises: 0d2634ef6bb6
Create Date: 2023-07-04 11:04:15.888923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2f6390dd52'
down_revision = '0d2634ef6bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_dataset', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ps_dialog_event_id_dataset_dataset'), 'dataset', ['id_dataset'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ps_dialog_event_id_dataset_dataset'), type_='foreignkey')
        batch_op.drop_column('id_dataset')

    # ### end Alembic commands ###
