"""remove unique constraint

Revision ID: 8ddf55e2ad28
Revises: 2ed77c795197
Create Date: 2023-05-30 17:48:06.146192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddf55e2ad28'
down_revision = '2ed77c795197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index('ix_dataset_name')
        batch_op.create_index(batch_op.f('ix_dataset_name'), ['name'], unique=False)

    with op.batch_alter_table('sm_post', schema=None) as batch_op:
        batch_op.drop_index('ix_sm_post_post_id')
        batch_op.create_index(batch_op.f('ix_sm_post_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('sm_reply', schema=None) as batch_op:
        batch_op.drop_index('ix_sm_reply_reply_id')
        batch_op.create_index(batch_op.f('ix_sm_reply_reply_id'), ['reply_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sm_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sm_reply_reply_id'))
        batch_op.create_index('ix_sm_reply_reply_id', ['reply_id'], unique=True)

    with op.batch_alter_table('sm_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sm_post_post_id'))
        batch_op.create_index('ix_sm_post_post_id', ['post_id'], unique=True)

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_name'))
        batch_op.create_index('ix_dataset_name', ['name'], unique=True)

    # ### end Alembic commands ###
