"""replace association table with object for thereapist annotation-scale

Revision ID: a99bd2e6e098
Revises: daf36d31eb2b
Create Date: 2023-12-12 10:57:36.111938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99bd2e6e098'
down_revision = 'daf36d31eb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationtherapist_annotationscale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_annotation_therapist', sa.Integer(), nullable=False),
    sa.Column('id_therapist_annotation_scale', sa.Integer(), nullable=False),
    sa.Column('is_additional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name=op.f('fk_annotationtherapist_annotationscale_id_ps_annotation_therapist_ps_annotation_therapist')),
    sa.ForeignKeyConstraint(['id_therapist_annotation_scale'], ['therapist_annotation_scale.id'], name=op.f('fk_annotationtherapist_annotationscale_id_therapist_annotation_scale_therapist_annotation_scale')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotationtherapist_annotationscale'))
    )
    op.drop_table('annotationtherapist_annotationschemascale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationtherapist_annotationschemascale',
    sa.Column('id_ps_annotation_therapist', sa.INTEGER(), nullable=True),
    sa.Column('id_therapist_annotation_scale', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name='fk_annotationtherapist_annotationschemascale_id_ps_annotation_therapist_ps_annotation_therapist'),
    sa.ForeignKeyConstraint(['id_therapist_annotation_scale'], ['therapist_annotation_scale.id'], name='fk_annotationtherapist_annotationschemascale_id_therapist_annotation_scale_therapist_annotation_scale')
    )
    op.drop_table('annotationtherapist_annotationscale')
    # ### end Alembic commands ###
