"""add timestamp column to dialog turn annotations

Revision ID: af0f84a7f301
Revises: f9cc1ee27357
Create Date: 2023-08-16 18:02:17.334073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0f84a7f301'
down_revision = 'f9cc1ee27357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ps_dialog_turn_annotation_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_dialog_turn_annotation_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
