"""add t_init and c_code columns to psychotherapy table

Revision ID: b09107c7f08f
Revises: e8caa616cab5
Create Date: 2023-06-23 15:59:15.597846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09107c7f08f'
down_revision = 'e8caa616cab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychotherapy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_init', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('c_code', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_psychotherapy_c_code'), ['c_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_psychotherapy_t_init'), ['t_init'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychotherapy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psychotherapy_t_init'))
        batch_op.drop_index(batch_op.f('ix_psychotherapy_c_code'))
        batch_op.drop_column('c_code')
        batch_op.drop_column('t_init')

    # ### end Alembic commands ###
