"""rename table to store client annotation labels

Revision ID: b1ef06d88844
Revises: 700345962f8e
Create Date: 2023-12-11 12:51:39.186532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ef06d88844'
down_revision = '700345962f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_annotation_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['client_annotation_label.id'], name=op.f('fk_client_annotation_label_parent_id_client_annotation_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_annotation_label')),
    sa.UniqueConstraint('label', 'parent_id', name=op.f('uq_client_annotation_label_label'))
    )
    with op.batch_alter_table('client_annotation_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_annotation_label_label'), ['label'], unique=False)

    with op.batch_alter_table('client_annotation_schema', schema=None) as batch_op:
        batch_op.drop_index('ix_client_annotation_schema_label')

    with op.batch_alter_table('annotationclient_annotationschema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_label', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_annotationclient_annotationschema_id_client_annotation_schema_client_annotation_schema', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationclient_annotationschema_id_client_annotation_label_client_annotation_label'), 'client_annotation_label', ['id_client_annotation_label'], ['id'])
        batch_op.drop_column('id_client_annotation_schema')

    with op.batch_alter_table('client_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_label', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_client_annotation_comment_id_client_annotation_schema_client_annotation_schema', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_client_annotation_comment_id_client_annotation_label_client_annotation_label'), 'client_annotation_label', ['id_client_annotation_label'], ['id'])
        batch_op.drop_column('id_client_annotation_schema')

    with op.batch_alter_table('client_annotation_scale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_label', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_client_annotation_scale_scale_title', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_client_annotation_scale_scale_title'), ['scale_title', 'scale_level', 'id_client_annotation_label'])
        batch_op.drop_constraint('fk_client_annotation_scale_id_client_annotation_schema_client_annotation_schema', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_client_annotation_scale_id_client_annotation_label_client_annotation_label'), 'client_annotation_label', ['id_client_annotation_label'], ['id'])
        batch_op.drop_column('id_client_annotation_schema')

    with op.batch_alter_table('evidence_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_label', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_evidence_client_id_client_annotation_schema_client_annotation_schema', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_evidence_client_id_client_annotation_label_client_annotation_label'), 'client_annotation_label', ['id_client_annotation_label'], ['id'])
        batch_op.drop_column('id_client_annotation_schema')

    op.drop_table('client_annotation_schema')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_schema', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_evidence_client_id_client_annotation_label_client_annotation_label'), type_='foreignkey')
        batch_op.create_foreign_key('fk_evidence_client_id_client_annotation_schema_client_annotation_schema', 'client_annotation_schema', ['id_client_annotation_schema'], ['id'])
        batch_op.drop_column('id_client_annotation_label')

    with op.batch_alter_table('client_annotation_scale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_schema', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_client_annotation_scale_id_client_annotation_label_client_annotation_label'), type_='foreignkey')
        batch_op.create_foreign_key('fk_client_annotation_scale_id_client_annotation_schema_client_annotation_schema', 'client_annotation_schema', ['id_client_annotation_schema'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_client_annotation_scale_scale_title'), type_='unique')
        batch_op.create_unique_constraint('uq_client_annotation_scale_scale_title', ['scale_title', 'scale_level', 'id_client_annotation_schema'])
        batch_op.drop_column('id_client_annotation_label')

    with op.batch_alter_table('client_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_schema', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_client_annotation_comment_id_client_annotation_label_client_annotation_label'), type_='foreignkey')
        batch_op.create_foreign_key('fk_client_annotation_comment_id_client_annotation_schema_client_annotation_schema', 'client_annotation_schema', ['id_client_annotation_schema'], ['id'])
        batch_op.drop_column('id_client_annotation_label')

    with op.batch_alter_table('annotationclient_annotationschema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_schema', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_annotationclient_annotationschema_id_client_annotation_label_client_annotation_label'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationclient_annotationschema_id_client_annotation_schema_client_annotation_schema', 'client_annotation_schema', ['id_client_annotation_schema'], ['id'])
        batch_op.drop_column('id_client_annotation_label')

    op.create_table('client_annotation_schema',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['client_annotation_schema.id'], name='fk_client_annotation_schema_parent_id_client_annotation_schema'),
    sa.PrimaryKeyConstraint('id', name='pk_client_annotation_schema'),
    sa.UniqueConstraint('label', 'parent_id', name='uq_client_annotation_schema_label')
    )
    with op.batch_alter_table('client_annotation_schema', schema=None) as batch_op:
        batch_op.create_index('ix_client_annotation_schema_label', ['label'], unique=False)

    with op.batch_alter_table('client_annotation_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_annotation_label_label'))

    op.drop_table('client_annotation_label')
    # ### end Alembic commands ###
