"""replace association table with object for dyad annotation-label

Revision ID: b316520ee5fd
Revises: 6e93ea750132
Create Date: 2023-12-12 16:15:29.566446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b316520ee5fd'
down_revision = '6e93ea750132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationdyad_annotationlabel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_annotation_dyad', sa.Integer(), nullable=False),
    sa.Column('id_dyad_annotation_label', sa.Integer(), nullable=False),
    sa.Column('is_additional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_label'], ['dyad_annotation_label.id'], name=op.f('fk_annotationdyad_annotationlabel_id_dyad_annotation_label_dyad_annotation_label')),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name=op.f('fk_annotationdyad_annotationlabel_id_ps_annotation_dyad_ps_annotation_dyad')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotationdyad_annotationlabel'))
    )
    op.drop_table('annotationdyad_annotationschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationdyad_annotationschema',
    sa.Column('id_ps_annotation_dyad', sa.INTEGER(), nullable=True),
    sa.Column('id_dyad_annotation_label', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_label'], ['dyad_annotation_label.id'], name='fk_annotationdyad_annotationschema_id_dyad_annotation_label_dyad_annotation_label'),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name='fk_annotationdyad_annotationschema_id_ps_annotation_dyad_ps_annotation_dyad')
    )
    op.drop_table('annotationdyad_annotationlabel')
    # ### end Alembic commands ###
