"""sm posts table

Revision ID: ba29fda317e7
Revises: 7d535da49440
Create Date: 2023-05-19 15:15:56.591506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba29fda317e7'
down_revision = '7d535da49440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sm_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('timeline_id', sa.String(length=64), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ldate', sa.DateTime(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('id_sm_annotation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_sm_annotation'], ['sm_annotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sm_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sm_post_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sm_post_timeline_id'), ['timeline_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sm_post_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sm_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sm_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_sm_post_timeline_id'))
        batch_op.drop_index(batch_op.f('ix_sm_post_post_id'))

    op.drop_table('sm_post')
    # ### end Alembic commands ###
