"""create strength label E for the client

Revision ID: baee7d5abf5e
Revises: 718b65826dce
Create Date: 2023-09-07 15:24:08.599508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baee7d5abf5e'
down_revision = '718b65826dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_e_client', sa.Enum('strength1', 'strength2', 'strength3', 'strength4', 'strength5', name='labelstrengtheclient'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_column('strength_e_client')

    # ### end Alembic commands ###
