"""update table to store dyad annotation comments

Revision ID: bc44a64ff9a3
Revises: ca308ae294c5
Create Date: 2023-12-12 16:49:57.673466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc44a64ff9a3'
down_revision = 'ca308ae294c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dyad_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_additional', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dyad_annotation_comment', schema=None) as batch_op:
        batch_op.drop_column('is_additional')

    # ### end Alembic commands ###
