"""summary comment for segment level annotations

Revision ID: c5d203a5ac98
Revises: 3e2a87f8c515
Create Date: 2023-09-13 11:29:39.441820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d203a5ac98'
down_revision = '3e2a87f8c515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.drop_column('comment_summary')

    # ### end Alembic commands ###
