"""ps dialog turn annotations

Revision ID: c610bdcfbe56
Revises: 8c2f6390dd52
Create Date: 2023-07-13 09:52:57.084492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c610bdcfbe56'
down_revision = '8c2f6390dd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_dialog_turn_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_a', sa.Enum('subcategory1', 'subcategory2', 'subcategory3', 'subcategory4', 'subcategory5', name='subcategoriesa'), nullable=True),
    sa.Column('category_b', sa.Enum('subcategory1', 'subcategory2', 'subcategory3', 'subcategory4', 'subcategory5', name='subcategoriesb'), nullable=True),
    sa.Column('category_c', sa.Enum('subcategory1', 'subcategory2', 'subcategory3', 'subcategory4', 'subcategory5', name='subcategoriesc'), nullable=True),
    sa.Column('category_d', sa.Enum('subcategory1', 'subcategory2', 'subcategory3', 'subcategory4', 'subcategory5', name='subcategoriesd'), nullable=True),
    sa.Column('category_e', sa.Enum('subcategory1', 'subcategory2', 'subcategory3', 'subcategory4', 'subcategory5', name='subcategoriese'), nullable=True),
    sa.Column('strength_a', sa.Enum('high', 'medium', 'low', name='labelstrength'), nullable=True),
    sa.Column('strength_b', sa.Enum('high', 'medium', 'low', name='labelstrength'), nullable=True),
    sa.Column('strength_c', sa.Enum('high', 'medium', 'low', name='labelstrength'), nullable=True),
    sa.Column('strength_d', sa.Enum('high', 'medium', 'low', name='labelstrength'), nullable=True),
    sa.Column('strength_e', sa.Enum('high', 'medium', 'low', name='labelstrength'), nullable=True),
    sa.Column('id_ps_dialog_turn', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_dialog_turn_annotation_id_dataset_dataset')),
    sa.ForeignKeyConstraint(['id_ps_dialog_turn'], ['ps_dialog_turn.id'], name=op.f('fk_ps_dialog_turn_annotation_id_ps_dialog_turn_ps_dialog_turn')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_dialog_turn_annotation'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ps_dialog_turn_annotation')
    # ### end Alembic commands ###
