"""update table to store therapist annotations

Revision ID: c99c9c8ababb
Revises: 3954c5c59575
Create Date: 2023-11-29 17:29:21.057131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99c9c8ababb'
down_revision = '3954c5c59575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_annotation_therapist', schema=None) as batch_op:
        batch_op.drop_column('strength_a')
        batch_op.drop_column('label_e')
        batch_op.drop_column('comment_d')
        batch_op.drop_column('label_c')
        batch_op.drop_column('comment_c')
        batch_op.drop_column('label_b')
        batch_op.drop_column('comment_a')
        batch_op.drop_column('comment_b')
        batch_op.drop_column('strength_c')
        batch_op.drop_column('strength_d')
        batch_op.drop_column('label_d')
        batch_op.drop_column('strength_e')
        batch_op.drop_column('label_a')
        batch_op.drop_column('comment_e')
        batch_op.drop_column('strength_b')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_annotation_therapist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_b', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('comment_e', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('label_a', sa.VARCHAR(length=9), nullable=True))
        batch_op.add_column(sa.Column('strength_e', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('label_d', sa.VARCHAR(length=14), nullable=True))
        batch_op.add_column(sa.Column('strength_d', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('strength_c', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('comment_b', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('comment_a', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('label_b', sa.VARCHAR(length=14), nullable=True))
        batch_op.add_column(sa.Column('comment_c', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('label_c', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('comment_d', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('label_e', sa.VARCHAR(length=19), nullable=True))
        batch_op.add_column(sa.Column('strength_a', sa.VARCHAR(length=6), nullable=True))

    # ### end Alembic commands ###
