"""replace association table with object for dyad annotation-scale

Revision ID: ca308ae294c5
Revises: b316520ee5fd
Create Date: 2023-12-12 16:38:12.827544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca308ae294c5'
down_revision = 'b316520ee5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationdyad_annotationscale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_annotation_dyad', sa.Integer(), nullable=False),
    sa.Column('id_dyad_annotation_scale', sa.Integer(), nullable=False),
    sa.Column('is_additional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_scale'], ['dyad_annotation_scale.id'], name=op.f('fk_annotationdyad_annotationscale_id_dyad_annotation_scale_dyad_annotation_scale')),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name=op.f('fk_annotationdyad_annotationscale_id_ps_annotation_dyad_ps_annotation_dyad')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotationdyad_annotationscale'))
    )
    op.drop_table('annotationdyad_annotationschemascale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationdyad_annotationschemascale',
    sa.Column('id_ps_annotation_dyad', sa.INTEGER(), nullable=True),
    sa.Column('id_dyad_annotation_scale', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_scale'], ['dyad_annotation_scale.id'], name='fk_annotationdyad_annotationschemascale_id_dyad_annotation_scale_dyad_annotation_scale'),
    sa.ForeignKeyConstraint(['id_ps_annotation_dyad'], ['ps_annotation_dyad.id'], name='fk_annotationdyad_annotationschemascale_id_ps_annotation_dyad_ps_annotation_dyad')
    )
    op.drop_table('annotationdyad_annotationscale')
    # ### end Alembic commands ###
