"""update annotations schema for client

Revision ID: d13127475c6c
Revises: 1ef00b5d0961
Create Date: 2023-10-17 16:34:21.937600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13127475c6c'
down_revision = '1ef00b5d0961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_annotation_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['client_annotation_schema.id'], name=op.f('fk_client_annotation_schema_parent_id_client_annotation_schema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_annotation_schema')),
    sa.UniqueConstraint('label', 'parent_id', name=op.f('uq_client_annotation_schema_label'))
    )
    with op.batch_alter_table('client_annotation_schema', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_annotation_schema_label'), ['label'], unique=False)

    with op.batch_alter_table('client_label', schema=None) as batch_op:
        batch_op.drop_index('ix_client_label_label')

    op.drop_table('client_label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_label',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['client_label.id'], name='fk_client_label_parent_id_client_label'),
    sa.PrimaryKeyConstraint('id', name='pk_client_label'),
    sa.UniqueConstraint('label', 'parent_id', name='uq_client_label_label')
    )
    with op.batch_alter_table('client_label', schema=None) as batch_op:
        batch_op.create_index('ix_client_label_label', ['label'], unique=False)

    with op.batch_alter_table('client_annotation_schema', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_annotation_schema_label'))

    op.drop_table('client_annotation_schema')
    # ### end Alembic commands ###
