"""association table between annotations and schema for client

Revision ID: d2a9e906e825
Revises: 36b6fa8c1f32
Create Date: 2023-10-24 13:47:18.853982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a9e906e825'
down_revision = '36b6fa8c1f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationclient_annotationschema',
    sa.Column('id_ps_annotation_client', sa.Integer(), nullable=True),
    sa.Column('id_client_annotation_schema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_schema'], ['client_annotation_schema.id'], name=op.f('fk_annotationclient_annotationschema_id_client_annotation_schema_client_annotation_schema')),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name=op.f('fk_annotationclient_annotationschema_id_ps_annotation_client_ps_annotation_client'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotationclient_annotationschema')
    # ### end Alembic commands ###
