"""rename association object for client annotation-label

Revision ID: d53eacbba78d
Revises: ea1290bacb2e
Create Date: 2023-12-11 17:41:58.772420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53eacbba78d'
down_revision = 'ea1290bacb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationclient_annotationlabel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_annotation_client', sa.Integer(), nullable=False),
    sa.Column('id_client_annotation_label', sa.Integer(), nullable=False),
    sa.Column('is_additional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_label'], ['client_annotation_label.id'], name=op.f('fk_annotationclient_annotationlabel_id_client_annotation_label_client_annotation_label')),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name=op.f('fk_annotationclient_annotationlabel_id_ps_annotation_client_ps_annotation_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotationclient_annotationlabel'))
    )
    op.drop_table('annotationclient_annotationschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationclient_annotationschema',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_ps_annotation_client', sa.INTEGER(), nullable=False),
    sa.Column('id_client_annotation_label', sa.INTEGER(), nullable=False),
    sa.Column('is_additional', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_annotation_label'], ['client_annotation_label.id'], name='fk_annotationclient_annotationschema_id_client_annotation_label_client_annotation_label'),
    sa.ForeignKeyConstraint(['id_ps_annotation_client'], ['ps_annotation_client.id'], name='fk_annotationclient_annotationschema_id_ps_annotation_client_ps_annotation_client'),
    sa.PrimaryKeyConstraint('id', name='pk_annotationclient_annotationschema')
    )
    op.drop_table('annotationclient_annotationlabel')
    # ### end Alembic commands ###
