"""update unique constraint in annotation schema scale models

Revision ID: d91305e2a856
Revises: 7b0e06654f54
Create Date: 2023-10-27 16:20:25.116297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91305e2a856'
down_revision = '7b0e06654f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_constraint('uq_client_annotation_schema_scale_scale_title', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_client_annotation_schema_scale_scale_title'), ['scale_title', 'scale_level', 'id_client_annotation_schema'])

    with op.batch_alter_table('dyad_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dyad_annotation_schema_scale_scale_title', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_dyad_annotation_schema_scale_scale_title'), ['scale_title', 'scale_level', 'id_dyad_annotation_schema'])

    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_constraint('uq_therapist_annotation_schema_scale_scale_title', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_therapist_annotation_schema_scale_scale_title'), ['scale_title', 'scale_level', 'id_therapist_annotation_schema'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapist_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_therapist_annotation_schema_scale_scale_title'), type_='unique')
        batch_op.create_unique_constraint('uq_therapist_annotation_schema_scale_scale_title', ['scale_title', 'id_therapist_annotation_schema'])

    with op.batch_alter_table('dyad_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_dyad_annotation_schema_scale_scale_title'), type_='unique')
        batch_op.create_unique_constraint('uq_dyad_annotation_schema_scale_scale_title', ['scale_title', 'id_dyad_annotation_schema'])

    with op.batch_alter_table('client_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_client_annotation_schema_scale_scale_title'), type_='unique')
        batch_op.create_unique_constraint('uq_client_annotation_schema_scale_scale_title', ['scale_title', 'id_client_annotation_schema'])

    # ### end Alembic commands ###
