"""add is_additional flag to dyad evidence table

Revision ID: d9e0fd219656
Revises: e6f36db7b44d
Create Date: 2023-12-12 17:20:02.935660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e0fd219656'
down_revision = 'e6f36db7b44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_dyad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_additional', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_dyad', schema=None) as batch_op:
        batch_op.drop_column('is_additional')

    # ### end Alembic commands ###
