"""replace association table with object for therapist annotation-label

Revision ID: daf36d31eb2b
Revises: d53eacbba78d
Create Date: 2023-12-11 18:32:49.772281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf36d31eb2b'
down_revision = 'd53eacbba78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationtherapist_annotationlabel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ps_annotation_therapist', sa.Integer(), nullable=False),
    sa.Column('id_therapist_annotation_label', sa.Integer(), nullable=False),
    sa.Column('is_additional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name=op.f('fk_annotationtherapist_annotationlabel_id_ps_annotation_therapist_ps_annotation_therapist')),
    sa.ForeignKeyConstraint(['id_therapist_annotation_label'], ['therapist_annotation_label.id'], name=op.f('fk_annotationtherapist_annotationlabel_id_therapist_annotation_label_therapist_annotation_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotationtherapist_annotationlabel'))
    )
    op.drop_table('annotationtherapist_annotationschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotationtherapist_annotationschema',
    sa.Column('id_ps_annotation_therapist', sa.INTEGER(), nullable=True),
    sa.Column('id_therapist_annotation_label', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_ps_annotation_therapist'], ['ps_annotation_therapist.id'], name='fk_annotationtherapist_annotationschema_id_ps_annotation_therapist_ps_annotation_therapist'),
    sa.ForeignKeyConstraint(['id_therapist_annotation_label'], ['therapist_annotation_label.id'], name='fk_annotationtherapist_annotationschema_id_therapist_annotation_label_therapist_annotation_label')
    )
    op.drop_table('annotationtherapist_annotationlabel')
    # ### end Alembic commands ###
