"""include moment of change for the client

Revision ID: e4c699f4e9a2
Revises: c5d203a5ac98
Create Date: 2023-09-14 14:57:42.960238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4c699f4e9a2"
down_revision = "c5d203a5ac98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "label_f_client",
                sa.Enum("no_change", "switch", "escalation", name="sublabelsfclient"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "strength_f_client",
                sa.Enum(
                    "significant_deterioration",
                    "some_deterioration",
                    "no_change",
                    "some_improvement",
                    "significant_improvement",
                    name="labelstrengthfclient",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("comment_f", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ps_dialog_turn_annotation", schema=None) as batch_op:
        batch_op.drop_column("comment_f")
        batch_op.drop_column("strength_f_client")
        batch_op.drop_column("label_f_client")

    # ### end Alembic commands ###
