"""update table to store dyad evidence events

Revision ID: e6f36db7b44d
Revises: bc44a64ff9a3
Create Date: 2023-12-12 16:55:41.862177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f36db7b44d'
down_revision = 'bc44a64ff9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_dyad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_dyad_annotation_label', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_evidence_dyad_id_dyad_annotation_label_dyad_annotation_label'), 'dyad_annotation_label', ['id_dyad_annotation_label'], ['id'])
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_dyad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=7), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_evidence_dyad_id_dyad_annotation_label_dyad_annotation_label'), type_='foreignkey')
        batch_op.drop_column('id_dyad_annotation_label')

    # ### end Alembic commands ###
