"""table for psychotherapy sessions

Revision ID: e8caa616cab5
Revises: 27d04d32c901
Create Date: 2023-06-22 13:25:37.978155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8caa616cab5'
down_revision = '27d04d32c901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychotherapy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_text', sa.Text(), nullable=True),
    sa.Column('event_speaker', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_psychotherapy_id_dataset_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_psychotherapy'))
    )
    with op.batch_alter_table('psychotherapy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psychotherapy_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychotherapy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psychotherapy_event_id'))

    op.drop_table('psychotherapy')
    # ### end Alembic commands ###
