"""add note column to evidence_client table

Revision ID: e9cc8bf05edd
Revises: 691476e11756
Create Date: 2023-09-27 10:53:41.521603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cc8bf05edd'
down_revision = '691476e11756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_client', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
