"""rename table to store dyad annotation scales

Revision ID: ea1290bacb2e
Revises: 358f46e37a0c
Create Date: 2023-12-11 16:58:05.778970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1290bacb2e'
down_revision = '358f46e37a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dyad_annotation_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_title', sa.String(length=64), nullable=False),
    sa.Column('scale_level', sa.String(length=64), nullable=False),
    sa.Column('id_dyad_annotation_label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_label'], ['dyad_annotation_label.id'], name=op.f('fk_dyad_annotation_scale_id_dyad_annotation_label_dyad_annotation_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dyad_annotation_scale')),
    sa.UniqueConstraint('scale_title', 'scale_level', 'id_dyad_annotation_label', name=op.f('uq_dyad_annotation_scale_scale_title'))
    )
    with op.batch_alter_table('dyad_annotation_scale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dyad_annotation_scale_scale_level'), ['scale_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_dyad_annotation_scale_scale_title'), ['scale_title'], unique=False)

    with op.batch_alter_table('dyad_annotation_schema_scale', schema=None) as batch_op:
        batch_op.drop_index('ix_dyad_annotation_schema_scale_scale_level')
        batch_op.drop_index('ix_dyad_annotation_schema_scale_scale_title')

    with op.batch_alter_table('annotationdyad_annotationschemascale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_dyad_annotation_scale', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_annotationdyad_annotationschemascale_id_dyad_annotation_schema_scale_dyad_annotation_schema_scale', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationdyad_annotationschemascale_id_dyad_annotation_scale_dyad_annotation_scale'), 'dyad_annotation_scale', ['id_dyad_annotation_scale'], ['id'])
        batch_op.drop_column('id_dyad_annotation_schema_scale')

    op.drop_table('dyad_annotation_schema_scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotationdyad_annotationschemascale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_dyad_annotation_schema_scale', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_annotationdyad_annotationschemascale_id_dyad_annotation_scale_dyad_annotation_scale'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationdyad_annotationschemascale_id_dyad_annotation_schema_scale_dyad_annotation_schema_scale', 'dyad_annotation_schema_scale', ['id_dyad_annotation_schema_scale'], ['id'])
        batch_op.drop_column('id_dyad_annotation_scale')

    op.create_table('dyad_annotation_schema_scale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scale_title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('scale_level', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id_dyad_annotation_label', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dyad_annotation_label'], ['dyad_annotation_label.id'], name='fk_dyad_annotation_schema_scale_id_dyad_annotation_label_dyad_annotation_label'),
    sa.PrimaryKeyConstraint('id', name='pk_dyad_annotation_schema_scale'),
    sa.UniqueConstraint('scale_title', 'scale_level', 'id_dyad_annotation_label', name='uq_dyad_annotation_schema_scale_scale_title')
    )
    with op.batch_alter_table('dyad_annotation_schema_scale', schema=None) as batch_op:
        batch_op.create_index('ix_dyad_annotation_schema_scale_scale_title', ['scale_title'], unique=False)
        batch_op.create_index('ix_dyad_annotation_schema_scale_scale_level', ['scale_level'], unique=False)

    with op.batch_alter_table('dyad_annotation_scale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dyad_annotation_scale_scale_title'))
        batch_op.drop_index(batch_op.f('ix_dyad_annotation_scale_scale_level'))

    op.drop_table('dyad_annotation_scale')
    # ### end Alembic commands ###
