"""update table to store client annotation comments

Revision ID: f247acbab109
Revises: eef2c39ab074
Create Date: 2023-12-05 14:23:25.685415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f247acbab109'
down_revision = 'eef2c39ab074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_annotationclient_annotationschema', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_client_annotation_comment_id_client_annotation_schema_client_annotation_schema', type_='foreignkey')
        batch_op.drop_constraint('fk_client_annotation_comment_id_ps_annotation_client_ps_annotation_client', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_client_annotation_comment_id_annotationclient_annotationschema_annotationclient_annotationschema'), 'annotationclient_annotationschema', ['id_annotationclient_annotationschema'], ['id'])
        batch_op.drop_column('id_client_annotation_schema')
        batch_op.drop_column('id_ps_annotation_client')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ps_annotation_client', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('id_client_annotation_schema', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_client_annotation_comment_id_annotationclient_annotationschema_annotationclient_annotationschema'), type_='foreignkey')
        batch_op.create_foreign_key('fk_client_annotation_comment_id_ps_annotation_client_ps_annotation_client', 'ps_annotation_client', ['id_ps_annotation_client'], ['id'])
        batch_op.create_foreign_key('fk_client_annotation_comment_id_client_annotation_schema_client_annotation_schema', 'client_annotation_schema', ['id_client_annotation_schema'], ['id'])
        batch_op.drop_column('id_annotationclient_annotationschema')

    # ### end Alembic commands ###
