"""rename psy dyad annotations table

Revision ID: f77d253b05cc
Revises: 87fe63ffa1a3
Create Date: 2023-09-26 15:16:56.799187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77d253b05cc'
down_revision = '87fe63ffa1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_annotation_dyad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('label_a', sa.Enum('bond', 'tasks_goals', name='sublabelsadyad'), nullable=True),
    sa.Column('label_b', sa.Enum('confrontational', 'withdrawal', 'other', name='sublabelsbdyad'), nullable=True),
    sa.Column('strength_a', sa.Enum('low', 'medium', 'high', name='labelstrengthadyad'), nullable=True),
    sa.Column('strength_b', sa.Enum('high', 'medium', 'low', name='labelstrengthbdyad'), nullable=True),
    sa.Column('comment_a', sa.Text(), nullable=True),
    sa.Column('comment_b', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_dataset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name=op.f('fk_ps_annotation_dyad_id_dataset_dataset')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_ps_annotation_dyad_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ps_annotation_dyad'))
    )
    with op.batch_alter_table('ps_annotation_dyad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ps_annotation_dyad_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('ps_dialog_turn_annotation_dyad', schema=None) as batch_op:
        batch_op.drop_index('ix_ps_dialog_turn_annotation_dyad_timestamp')

    with op.batch_alter_table('annotationsdyad_dialogturn', schema=None) as batch_op:
        batch_op.drop_constraint('fk_annotationsdyad_dialogturn_id_annotation_dyad_ps_dialog_turn_annotation_dyad', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annotationsdyad_dialogturn_id_annotation_dyad_ps_annotation_dyad'), 'ps_annotation_dyad', ['id_annotation_dyad'], ['id'])

    op.drop_table('ps_dialog_turn_annotation_dyad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotationsdyad_dialogturn', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_annotationsdyad_dialogturn_id_annotation_dyad_ps_annotation_dyad'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annotationsdyad_dialogturn_id_annotation_dyad_ps_dialog_turn_annotation_dyad', 'ps_dialog_turn_annotation_dyad', ['id_annotation_dyad'], ['id'])

    op.create_table('ps_dialog_turn_annotation_dyad',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('label_a', sa.VARCHAR(length=11), nullable=True),
    sa.Column('label_b', sa.VARCHAR(length=15), nullable=True),
    sa.Column('strength_a', sa.VARCHAR(length=6), nullable=True),
    sa.Column('strength_b', sa.VARCHAR(length=6), nullable=True),
    sa.Column('comment_a', sa.TEXT(), nullable=True),
    sa.Column('comment_b', sa.TEXT(), nullable=True),
    sa.Column('comment_summary', sa.TEXT(), nullable=True),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.Column('id_dataset', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset.id'], name='fk_ps_dialog_turn_annotation_dyad_id_dataset_dataset'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='fk_ps_dialog_turn_annotation_dyad_id_user_user'),
    sa.PrimaryKeyConstraint('id', name='pk_ps_dialog_turn_annotation_dyad')
    )
    with op.batch_alter_table('ps_dialog_turn_annotation_dyad', schema=None) as batch_op:
        batch_op.create_index('ix_ps_dialog_turn_annotation_dyad_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('ps_annotation_dyad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ps_annotation_dyad_timestamp'))

    op.drop_table('ps_annotation_dyad')
    # ### end Alembic commands ###
