"""rename category to label

Revision ID: f9cc1ee27357
Revises: 77807f9373ae
Create Date: 2023-07-14 16:32:22.541555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cc1ee27357'
down_revision = '77807f9373ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_a', sa.Enum('sublabel1', 'sublabel2', 'sublabel3', 'sublabel4', 'sublabel5', name='sublabelsa'), nullable=True))
        batch_op.add_column(sa.Column('label_b', sa.Enum('sublabel1', 'sublabel2', 'sublabel3', 'sublabel4', 'sublabel5', name='sublabelsb'), nullable=True))
        batch_op.add_column(sa.Column('label_c', sa.Enum('sublabel1', 'sublabel2', 'sublabel3', 'sublabel4', 'sublabel5', name='sublabelsc'), nullable=True))
        batch_op.add_column(sa.Column('label_d', sa.Enum('sublabel1', 'sublabel2', 'sublabel3', 'sublabel4', 'sublabel5', name='sublabelsd'), nullable=True))
        batch_op.add_column(sa.Column('label_e', sa.Enum('sublabel1', 'sublabel2', 'sublabel3', 'sublabel4', 'sublabel5', name='sublabelse'), nullable=True))
        batch_op.drop_column('category_c')
        batch_op.drop_column('category_b')
        batch_op.drop_column('category_e')
        batch_op.drop_column('category_d')
        batch_op.drop_column('category_a')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ps_dialog_turn_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_a', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('category_d', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('category_e', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('category_b', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('category_c', sa.VARCHAR(length=12), nullable=True))
        batch_op.drop_column('label_e')
        batch_op.drop_column('label_d')
        batch_op.drop_column('label_c')
        batch_op.drop_column('label_b')
        batch_op.drop_column('label_a')

    # ### end Alembic commands ###
