"""update table to store evidence events for client

Revision ID: fd4804e93b31
Revises: fdc4ed98f60e
Create Date: 2023-12-08 13:34:25.770439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4804e93b31'
down_revision = 'fdc4ed98f60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_client_annotation_schema', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_additional', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_evidence_client_id_client_annotation_schema_client_annotation_schema'), 'client_annotation_schema', ['id_client_annotation_schema'], ['id'])
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=7), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_evidence_client_id_client_annotation_schema_client_annotation_schema'), type_='foreignkey')
        batch_op.drop_column('is_additional')
        batch_op.drop_column('id_client_annotation_schema')

    # ### end Alembic commands ###
