"""is_additional flag for client annotation comments table

Revision ID: fdc4ed98f60e
Revises: eef2c39ab074
Create Date: 2023-12-07 11:46:48.121819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc4ed98f60e'
down_revision = 'eef2c39ab074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_annotation_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_additional', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_annotation_comment', schema=None) as batch_op:
        batch_op.drop_column('is_additional')

    # ### end Alembic commands ###
