# GitHub Action for running prettier - see https://github.com/creyD/prettier_action
name: prettier-action

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # files will not be changed, only checked
          dry: True
          # check only HTML, Yaml, JSON and Markdown files
          prettier_options: --check **/*.{html,yaml,yml,json,md}
